---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      become: true
      become_method: sudo
      apt: name=nginx state=latest 
    - name: start nginx
      service:
          name: nginx
          state: started
