---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest force_apt_get=True
    - name: start nginx
      service:
          name: nginx
          state: started
